# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160510_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
