# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('tasks', 'Category')
    db_alias = schema_editor.connection.alias

    Category.objects.using(db_alias).bulk_create([
        Category(name='Task'),
        Category(name='Bug'),
        Category(name='Enhancement'),
    ])

def create_default_priorities(apps, schema_editor):
    Priority = apps.get_model('tasks', 'Priority')
    db_alias = schema_editor.connection.alias

    Priority.objects.using(db_alias).bulk_create([
        Priority(name='Low'),
        Priority(name='Normal'),
        Priority(name='High'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_project_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Category')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Priority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Project')),
            ],
        ),
        migrations.RunPython(create_default_categories),
        migrations.RunPython(create_default_priorities),
    ]
