# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_category_priority_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
