# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_time', models.PositiveIntegerField()),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.Comment')),
            ],
        ),
    ]
