# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_comment_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 25, 16, 39, 10, 872510, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
