# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def create_default_states(apps, schema_editor):
    TaskState = apps.get_model('tasks', 'TaskState')
    db_alias = schema_editor.connection.alias

    TaskState.objects.using(db_alias).bulk_create([
        TaskState(name='New'),
        TaskState(name='Closed'),
        TaskState(name='Invalid'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20160525_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RunPython(create_default_states),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskState'),
        ),
    ]
