# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20160607_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-default', '-created_date']},
        ),
        migrations.AddField(
            model_name='task',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
