# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20160623_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='per_hour',
            field=models.PositiveSmallIntegerField(default=150),
        ),
    ]
